### PR TITLE
add screenshot carousel, hide existing feature block

### PR DESCRIPTION
**Pull request by bburns**
Here's the carousel - I'm a bit on the fence about it. 

When I was checking out the spacemacs site the screenshots were what I latched onto - I didn't want to read a lot, just wanted to see what it did. 

And I hid the existing feature list in this commit but maybe it would be good to have both, even if they duplicate each other a bit. 

So, it's up to you if you want to use it - we could also increase the size of the front page a bit, to bump it to the second page.

### CODE REVIEW

**Comment by NicolasPetton** [comment]
I'll pull this PR locally and will have a look. However, I see that in the screenshots you are not using the default Gnome theme. Could you fix that?

**Comment by bburns** [comment]
Here's a screenshot also - if we used it it would probably be good if it included the existing feature list also, maybe called the carousel Screenshots or First look or just have no title. 

esite-carousel

**Comment by NicolasPetton** [comment]
I agree, I want to keep the existing feature list.

The carroussel could be used in place of the current screenshot, with the following modifications:
- use the Gnome theme
- try to keep the same size & ratio for the new screenshots
- the screenshot don't have to show a full Emacs window, some partial sceenshots might be just fine (and more focus, so it might be even better)
- maybe keep the current screenshot as the first item of the carroussel?

**Comment by bburns** [comment]
Okay, I'll try that - when I took the screenshots I had missed that you had some in the images folder already, so there was some duplication - I'll merge them and add the Hello shot and customization screen also. 

Though I'm not sure what the optimal number of screenshots would be - 5, 6, 7? Wouldn't want the user to feel like they have to click through too many. Maybe 5 is good. 

And I'll try increasing the size of the front page a bit to bump the screenshots to the second page, and see how it looks. 

I'll also reduce the existing images to 8-bits to make the files smaller.

**Pull request closed without merging**
